version: "3.9"
services:
  codesh:
    build: ./codesh/
    env_file:
      - ./login.env
  # startupbase:
  #   build: ./startupbase/
  #   env_file:
  #     # - ./template_enviroments_variables.env
  # slintel:
  #   build: ./slintel/
  #   env_file:
  #     # - ./template_enviroments_variables.env
  # thor:
  #   build: ./thor/
  #   env_file:
  #     - ./template_enviroments_variables.env
