version: "3.9"
services:
  backend:
    build: ./backend/
    env_file:
      - ~/.secret/psql.env
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    env_file:
    - ~/.secret/firebase.env
    ports:
      - "3000:3000"
    depends_on: [backend]

