version: "3.9"
services:
  backend:
    build: ./backend/
    env_file:
      - ../environments_variables/backend.env
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: ${PWD}/frontend
      target: /frontend
    depends_on: [backend]
