version: "3.9"
services:
  backend:
    build: ./backend/
    env_file:
      - ~/.secret/psql.env
    ports:
      - "8000:8000"
    volumes:
    - type: bind
      source: ${PWD}/backend
      target: /backend
  frontend:
    build: ./frontend/
    env_file:
    - ~/.secret/firebase.env
    ports:
      - "3000:3000"
    volumes:
    - type: bind
      source: ${PWD}/frontend
      target: /frontend
    depends_on: [backend]
