name: xavier

on:
  push:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        mkdir ~/.secret
        touch ~/.secret/psql.env ~/.secret/firebase.env
    - name: tests
      run: bash ./api/run_compose.sh test
      env:
        DBHOST: ${{ secrets.DBHOST }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPASS: ${{ secrets.DBPASS }}
        DBPORT: ${{ secrets.DBPORT }}
        DBNAME: ${{ secrets.DBNAME }}
