name: xavier

on:
  push:
    paths:
    - 'api/**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: setup
      run: |
        mkdir ~/.secret
        touch ~/.secret/firebase.env
        echo "DBHOST=${{ secrets.DBHOST }}
        DBUSER=${{ secrets.DBUSER }}
        DBPASS=${{ secrets.DBPASS }}
        DBPORT=${{ secrets.DBPORT }}
        DBNAME=${{ secrets.DBNAME }}
        APIKEY=${{ secrets.APIKEY }}
        AUTHDOMAIN=${{ secrets.AUTHDOMAIN }}
        PROJECTID=${{ secrets.PROJECTID }}
        STORAGEBUCKET=${{ secrets.STORAGEBUCKET }}
        MESSAGINGSENDERID=${{ secrets.MESSAGINGSENDERID }}
        APPID=${{ secrets.APPID }}
        MEASUREMENTID=${{ secrets.MEASUREMENTID }}" > ~/.secret/psql.env

    - name: react tests
      run: |
        cd api/frontend
        npm install
        npm test

    - name: selenium tests
      run: |
        cd api
        bash run_compose.sh test
