name: xavier

on:
  push:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: get secrets
      env:
        DBHOST: ${{ secrets.DBHOST }}
        DBUSER: ${{ secrets.DBUSER }}
        DBPASS: ${{ secrets.DBPASS }}
        DBPORT: ${{ secrets.DBPORT }}
        DBNAME: ${{ secrets.DBNAME }}
        APIKEY: ${{ secrets.APIKEY }}
        AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
        PROJECTID: ${{ secrets.PROJECTID }}
        STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
        MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
        APPID: ${{ secrets.APPID }}
        MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
    - uses: actions/checkout@v2
    - name: setup
      run: |
        mkdir ~/.secret
        touch ~/.secret/psql.env ~/.secret/firebase.env
    - name: tests
      run: |
        cd api
        bash run_compose.sh test
        cd ..
